CREATE TABLE "Users" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FullName" varchar(255),
  "Email" varchar(255) UNIQUE NOT NULL,
  "PasswordHash" varchar(512) NOT NULL,
  "CreatedAt" timestamptz NOT NULL DEFAULT (now()),
  "IsDeleted" bool NOT NULL DEFAULT false
);

CREATE TABLE "Roles" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RoleName" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "UserRoles" (
  "UserId" int,
  "RoleId" int,
  PRIMARY KEY ("UserId", "RoleId")
);

CREATE TABLE "Stores" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "StoreName" varchar(255) NOT NULL,
  "Address" varchar(500),
  "CreatedAt" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "StoreStaff" (
  "UserId" int,
  "StoreId" int,
  PRIMARY KEY ("UserId", "StoreId")
);

CREATE TABLE "Categories" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ParentCategoryId" int,
  "Name" varchar(255) NOT NULL,
  "CreatedAt" timestamptz NOT NULL DEFAULT (now()),
  "ModifiedAt" timestamptz,
  "ModifiedById" int
);

CREATE TABLE "Brands" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BrandName" varchar(255) NOT NULL
);

CREATE TABLE "Products" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BrandId" int,
  "ProductName" varchar(500) NOT NULL,
  "Description" text,
  "CreatedAt" timestamptz NOT NULL DEFAULT (now()),
  "IsDeleted" bool NOT NULL DEFAULT false,
  "ModifiedAt" timestamptz,
  "ModifiedById" int
);

CREATE TABLE "ProductCategories" (
  "ProductId" int,
  "CategoryId" int,
  PRIMARY KEY ("ProductId", "CategoryId")
);

CREATE TABLE "StoreInventories" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "StoreId" int NOT NULL,
  "ProductId" int NOT NULL,
  "Price" decimal(10,2) NOT NULL,
  "Quantity" int NOT NULL DEFAULT 0,
  "ModifiedAt" timestamptz,
  "ModifiedById" int
);

CREATE TABLE "ShippingAddresses" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int NOT NULL,
  "AddressLine1" varchar(500) NOT NULL,
  "City" varchar(100),
  "PostalCode" varchar(20),
  "IsDefault" bool DEFAULT false
);

CREATE TABLE "Orders" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int NOT NULL,
  "StoreId" int NOT NULL,
  "ShippingAddressId" int,
  "TotalAmount" decimal(10,2) NOT NULL,
  "CurrentStatus" varchar(50) DEFAULT 'Pending',
  "CreatedAt" timestamptz NOT NULL DEFAULT (now()),
  "ModifiedAt" timestamptz,
  "ModifiedById" int
);

CREATE TABLE "OrderItems" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OrderId" int NOT NULL,
  "ProductId" int NOT NULL,
  "Quantity" int NOT NULL,
  "PriceAtPurchase" decimal(10,2) NOT NULL
);

CREATE TABLE "OrderStatusHistory" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OrderId" int NOT NULL,
  "Status" varchar(50) NOT NULL,
  "ChangedAt" timestamptz NOT NULL DEFAULT (now()),
  "ChangedById" int
);

CREATE TABLE "PaymentMethods" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MethodName" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "Payments" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OrderId" int NOT NULL,
  "PaymentMethodId" int NOT NULL,
  "Amount" decimal(10,2) NOT NULL,
  "PaymentDate" timestamptz NOT NULL DEFAULT (now()),
  "TransactionId" varchar(255)
);

CREATE UNIQUE INDEX ON "StoreInventories" ("StoreId", "ProductId");

COMMENT ON COLUMN "OrderItems"."PriceAtPurchase" IS 'Ціна, зафіксована на момент покупки';

COMMENT ON COLUMN "OrderStatusHistory"."ChangedById" IS 'NULL, якщо змінено системою';

ALTER TABLE "UserRoles" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("Id");

ALTER TABLE "UserRoles" ADD FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id");

ALTER TABLE "StoreStaff" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("Id");

ALTER TABLE "StoreStaff" ADD FOREIGN KEY ("StoreId") REFERENCES "Stores" ("Id");

ALTER TABLE "Categories" ADD FOREIGN KEY ("ParentCategoryId") REFERENCES "Categories" ("Id");

ALTER TABLE "Categories" ADD FOREIGN KEY ("ModifiedById") REFERENCES "Users" ("Id");

ALTER TABLE "Products" ADD FOREIGN KEY ("BrandId") REFERENCES "Brands" ("Id");

ALTER TABLE "Products" ADD FOREIGN KEY ("ModifiedById") REFERENCES "Users" ("Id");

ALTER TABLE "ProductCategories" ADD FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id");

ALTER TABLE "ProductCategories" ADD FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id");

ALTER TABLE "StoreInventories" ADD FOREIGN KEY ("StoreId") REFERENCES "Stores" ("Id");

ALTER TABLE "StoreInventories" ADD FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id");

ALTER TABLE "StoreInventories" ADD FOREIGN KEY ("ModifiedById") REFERENCES "Users" ("Id");

ALTER TABLE "ShippingAddresses" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("Id");

ALTER TABLE "Orders" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("Id");

ALTER TABLE "Orders" ADD FOREIGN KEY ("StoreId") REFERENCES "Stores" ("Id");

ALTER TABLE "Orders" ADD FOREIGN KEY ("ShippingAddressId") REFERENCES "ShippingAddresses" ("Id");

ALTER TABLE "Orders" ADD FOREIGN KEY ("ModifiedById") REFERENCES "Users" ("Id");

ALTER TABLE "OrderItems" ADD FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id");

ALTER TABLE "OrderItems" ADD FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id");

ALTER TABLE "OrderStatusHistory" ADD FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id");

ALTER TABLE "OrderStatusHistory" ADD FOREIGN KEY ("ChangedById") REFERENCES "Users" ("Id");

ALTER TABLE "Payments" ADD FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id");

ALTER TABLE "Payments" ADD FOREIGN KEY ("PaymentMethodId") REFERENCES "PaymentMethods" ("Id");
